defaults: &defaults
  reserved_screen_name_list: ["200", "400", "403", "404", "422", "500", "503", about, account, accounts,
                              admin, alpha, api, beta,
                              block, blog, bookmark, bookmarks, comment, comments,
                              contact, contacts, entry, entries, example,
                              favorite, favorites, faq, find, follow, followers, following,
                              help, helps, home, inbox, jobs, list, lists, login, logout,
                              mention, mentions,
                              privacy, profile, profiles, public, remove, replies, reply, root, rss,
                              search, setting, settings, signout, signup, status,
                              tag, tags, terms, test, tests, timeline,
                              unfollow, update, updates, user, users]

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults